// Generated by Wrangler on Wed Aug 21 2024 17:23:47 GMT+0200 (Central European Summer Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	WEBHOOK_RECEIVER: DurableObjectNamespace<import("./src/index").WebhookReceiver>;
}
